# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRCodeScan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QRCodeScan
  
  pod 'Realm', '~> 3.7.4'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveObjC', '~> 3.1.0'
  
end
